# Generated by Django 4.2.16 on 2024-10-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(max_length=200, verbose_name='Место')),
                ('data_time', models.DateTimeField(verbose_name='Дата и время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('is_nice_way', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.IntegerField(verbose_name='Периодичность в днях')),
                ('reward', models.CharField(max_length=200, verbose_name='Вознаграждение')),
                ('units_measurement', models.CharField(blank=True, choices=[('SS', 'Секунды'), ('HH', 'Часы'), ('MM', 'Минуты')], max_length=2, null=True, verbose_name='Еденицы измерения времени выполнения')),
                ('time_execution', models.IntegerField(verbose_name='Время в выбраных еденицых измерения')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('associated_way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.way', verbose_name='Связанная привычка')),
            ],
        ),
    ]
