# Generated by Django 4.2.16 on 2024-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение'),
        ),
    ]
