# Generated by Django 4.2.16 on 2024-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_way_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='units_measurement',
        ),
        migrations.AlterField(
            model_name='way',
            name='time_execution',
            field=models.IntegerField(verbose_name='Время в секундах'),
        ),
    ]
